version: '3.8'

services:
  openmemory:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OM_PORT=8080
      - OM_DB_PATH=/data/openmemory.sqlite
      - OM_API_KEY=${OM_API_KEY:-}
      - OM_EMBEDDINGS=${OM_EMBEDDINGS:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OM_VEC_DIM=${OM_VEC_DIM:-1536}
      - OM_MIN_SCORE=${OM_MIN_SCORE:-0.3}
      - OM_DECAY_LAMBDA=${OM_DECAY_LAMBDA:-0.02}
    volumes:
      - openmemory_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  openmemory_data:
    driver: local